version: '3.8'

services:

  django:
    build: .
    container_name: djangoproject
    restart: always
    command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn app.wsgi:application -b 0.0.0.0:5353"
    env_file:
      - .env
    volumes:
      - ./app:/app/
      - /app/static:/static
      - /app/media:/media
    expose:
     - "5353"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: nginxproject
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - /app/static:/static
      - /app/media:/media
    ports:
      - "5353:5353"
    depends_on:
      - django

  db:
    image: postgres:13
    container_name: postgresproject
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres-project:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  postgres-project:
    external: true



    

