version: '3.8'

services:

  django:
    build: .
    container_name: djangoprojetoint
    command: "gunicorn app.wsgi:application --bind 0.0.0.0:5353 --reload"
    env_file:
      - .env
    volumes:
      - ./app:/app/
    expose:
     - "5353"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginxprojetoint
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "5353:5353"
    depends_on:
      - django

  
  db:
    image: postgres:13
    container_name: postgresprojetoint
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
    external: true



    

