# Generated by Django 3.2.14 on 2022-07-08 12:52

import django.core.validators
from django.db import migrations, models
import gabaystore.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(upload_to='images/', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size])),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('clothing_type', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Hoodie', 'Hoodie'), ('Shirt', 'Shirt')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[gabaystore.validators.validate_price])),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30), gabaystore.validators.validate_quantity])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Cloth',
            },
        ),
    ]
