# Generated by Django 4.1 on 2022-08-22 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gabaystore.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True, validators=[gabaystore.validators.validate_name])),
                ('picture', models.ImageField(null=True, upload_to='media', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size])),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True, validators=[gabaystore.validators.validate_size])),
                ('clothing_type', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Hoodie', 'Hoodie'), ('Shirt', 'Shirt')], max_length=20, null=True, validators=[gabaystore.validators.validate_clothing_type])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True)),
                ('users_wishlist', models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_order', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid_status', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabaystore.cloth')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabaystore.order')),
            ],
        ),
    ]
