# Generated by Django 4.0.6 on 2022-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloth',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table=None,
        ),
    ]
