# Generated by Django 3.2.14 on 2022-07-10 05:44

from django.db import migrations, models
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='clothing_type',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Hoodie', 'Hoodie'), ('Shirt', 'Shirt')], max_length=20, validators=[gabaystore.validators.validate_clothing_type]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[gabaystore.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, validators=[gabaystore.validators.validate_size]),
        ),
    ]
