# Generated by Django 4.0.6 on 2022-08-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gabaystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='media', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
