# Generated by Django 4.1 on 2022-08-23 14:43

from django.db import migrations, models
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size]),
        ),
    ]
