# Generated by Django 3.2.14 on 2022-07-06 22:07

from django.db import migrations, models
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='images/', validators=[gabaystore.validators.validate_file_type]),
        ),
    ]
