# Generated by Django 3.2.14 on 2022-07-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gabaystore', '0002_auto_20220710_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[gabaystore.validators.validate_price])),
                ('paid_status', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='process', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CartOrder',
            },
        ),
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size]),
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[gabaystore.validators.validate_quantity])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[gabaystore.validators.validate_price])),
                ('invoice', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(upload_to='', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabaystore.cloth')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabaystore.cartorder')),
            ],
            options={
                'db_table': 'CartOrderItems',
            },
        ),
    ]
