# Generated by Django 4.0.6 on 2022-08-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
