# Generated by Django 3.2.14 on 2022-07-04 21:55

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0002_alter_cloth_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='images/', variations={'thumbnail': (100, 100)}),
        ),
    ]
