# Generated by Django 3.2.14 on 2022-07-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0002_alter_cloth_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
