# Generated by Django 4.0.6 on 2022-07-21 22:33

from django.db import migrations, models
import gabaystore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gabaystore', '0003_auto_20220711_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='media/', validators=[gabaystore.validators.validate_file_name, gabaystore.validators.validate_file_extension_and_size]),
        ),
    ]
