# Generated by Django 4.1 on 2022-08-21 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gabaystore', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
